README.rst
The old news were misleading because they suggest that this project has been last updated in 2011. It seems to me that actually this projects is alive and actively maintained.
=> Remove old news from README.md

README.rst, aldjemy/meta.py
Using this metaclass, all callables and properties get exposed
automatically and you don't need to create a separate mixin class.
=> Add aldjemy.meta.AldjemyMeta for easier mixins

aldjemy/orm.py
According SqlAlchemy documentation should use sessionmaker instead of create_session 
From changelog version 0.6.4:
The Session class is now present in sqlalchemy.orm.*. We’re moving away from the usage of create_session(), which has non-standard defaults, for those situations where a one-step Session constructor is desired. Most users should stick with sessionmaker() for general use, however.
=> Change orm session creation

aldjemy/orm.py
Do not add SQLAlchemy backrefs to relationships if the Django field name ends with '+' (eg: duplicate Django's ORM behavior).
Note that this is off-the-cuff, and completely untested.
Hopefully closes #14.
=> Optionally skip adding SQLAlchemy backrefs

aldjemy/table.py
New field type added in Django 1.8. This closes #30.
=> Add support for DurationField.

aldjemy/core.py
This addresses the new comment for #15 as well as issue #29 .
Since it just sets up a property in the `_ConnectRecord` initializer and adds a keyword argument to `invalidate()`, it won't have any backwards compatibility issues with previous SQLAlchemy versions.
=> Fixes for SQLAlchemy 1.0.6 compatibility.

README.rst
README was referencing `trafaret` instead of `aldjemy` on pypi.
=> Fix pypi graphics

aldjemy/core.py, aldjemy/orm.py, test_project/sample/models.py, test_project/sample/tests.py
This pull request aims to resolve an exception
```
sqlalchemy.exc.ArgumentError: Class '<class 'aldjemy.orm.C'>' already has a primary mapper defined. Use non_primary=True to create a non primary Mapper.  clear_mappers() will remove *all* current mappers from all classes.
```
in **prepare_models** function when it deals with a proxy model inherited from another model sub-type.
In particular this fix supports the following inheritance scenario:
```
class A(model.Model):
pass
class B(A):
pass
class C(B):
class Meta:
proxy = True
```
=> A fix for sqlalchemy.exc.ArgumentError in prepare_models

setup.py
by doing that, djangopackages.org can mark this package as python3 ready. Also pypi analyses will also show this package as python3 ready
=> Added python 3 to classifiers

aldjemy/orm.py
The 'uselist' parameter to backref should be False for OneToOneFields as per http://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html#one-to-one. Otherwise, calling the backref accessor on the model will return an InstrumentedList
=> Fix bug with backrefs on OneToOne fields

aldjemy/orm.py
By default in Django the column name in database is chosen based on field name in model. However it is possible to override the column name using the [`db_column`][1] property.
In our project we use quite obscure column names like `F_ARTICLE_NAME` when the field name is just `name`. In Aldjemy ORM, we want to use the field name, not the column name. Without this change, it is only possible for related keys (such as ForeignKey and OneToOneField), but not for normal keys.
[1]: https://docs.djangoproject.com/en/dev/ref/models/fields/#db-column
=> orm: Map non-related fields too, to make them accessible by name

aldjemy/orm.py, test.sh, test_project_postgres/sample/models.py, test_project_postgres/sample/tests.py, tox.ini
I'm not sure exactly why my field isn't in the columns it's looking up, but it's a `django.contrib.postgres.fields.JSONField`, and it likely has something to do with that. Anyway, just checking to ensure it is indeed in the dict of columns is good enough to solve the issue for me.
Fixes #65
=> Ignore missing columns

aldjemy/core.py, aldjemy/orm.py
This PR provides the ability for external clients to provide json_deserializer. This custom json_deserializer will then be used to configure sqlalchemy json_deserializer
=> Support configuring sqlalchemy with custom json_deserializer 

.github/workflows/build.yml, .gitignore, test_project/sample/routers.py, test_project/sample/tests.py, tox.ini
Include Django 2.2 and 3.0, and matching Python versions. No deprecation of supporting versions is included, as that will require a major version bump, so I'm inclined to not bother until its necessary.
I expect test failures, something about `django_content_type` not existing. I don't know the solution yet, but it only seems to affect the tests, as I'm running this library in production on Django 3.0 right now.
References #90
=> Expand support matrix

.github/workflows/build.yml, README.rst, setup.py, test.sh, tox.ini
=> Remove support for deprecated python and django versions

poetry.lock, pyproject.toml, test_project/frozen.txt, test_project/requirements.txt
Remove requirements.txt files
This will make the recent PRs from dependabot obsolete. The requirements files are already not being used, AFAICT.
=> Add Django to dependencies

poetry.lock, pyproject.toml, tox.ini
This allows updates to happen, but we don't want to keep pinned to SQLAlchemy <1.4. If we don't get it figured out soon, though, we may have to release something without support for SQLAlchemy 1.4+.
=> Pin SQLAlchemy <1.4

HISTORY.rst, aldjemy/apps.py, aldjemy/core.py, aldjemy/orm.py
I'm going heavy in removing some public interfaces that I think are unwise. This is a breaking release. The core functionality, the `sa` attribute, will not be broken, but I'm hoping that along the way we can just get rid of the `Cache`. I think it's a misfeature. These are some steps in that potential direction.
=> Remove some unwise public interfaces

HISTORY.rst, aldjemy/core.py, aldjemy/orm.py
Taken from #291 with some minor modification. Thank you, @tim-schilling!
This does not add SQLAlchemy 2.0 compatibility.
=> Add a setting to force future mode

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, HISTORY.rst, README.rst, pyproject.toml, tox.ini
I was running into some trouble using `poetry` to do installs. Technically, I could have just used `pip` to install the same as I have here, since `poetry` provides a build backend. However, it seems that poetry has some conflicts in strategy with the broader python community, and I think that the community has valid criticisms. Poetry has done the community a great service with its opinionated approach that drove the ecosystem forward. Thankfully, the tooling has matured, and we have other options that are great and make different trade-offs. For this project, `hatch`'s backend `hatchling` seems like a really good fit.
=> Switch to hatchling

.github/workflows/build.yml, tox.ini
So that I can run pytest without additional arguments, use the `pythonpath` configuration to include the working directory by default.
=> Clean pytest

HISTORY.rst, aldjemy/apps.py, aldjemy/orm.py, aldjemy/session.py, test_project/pg/tests.py, test_project/sample/tests.py
While I've been long thinking it, the issues figuring out compatibility for SQLAlchemy 2.0 have cemented for me that the model generation should be considered separately from the session handling. Aldjemy combines these two subsystems in a really neat way, but the model generation is worthwhile even if the session handling isn't working right.
Since I'm currently having some trouble upgrading the deep internals of the session handling, and because it seems like a proper boundary anyway, I want to lean into that a bit and split things up that way.
To simplify things, this also includes some breaking changes, noted in the HISTORY file. These changes are not important enough to prompt a release yet, but I believe will help us maintain this project.
=> Decouple model generation from the session magic

.github/workflows/build.yml
This should hopefully fix our flaky codecov uploads
=> Use our own codecov token
