aldjemy/aldjemy

- aldjemy/meta.py
- test_project/sample/models.py
- test_project/sample/tests.py
Well, having no tests for #22 was no good after all, as the metaclass didn't work. I fixed the bug and added tests.
> AldjemyMeta: Fix an import, add tests

- aldjemy/table.py
BigAutoField is one of the upcoming Django version's features, see https://github.com/django/django/pull/4970
> Add support for BigAutoField

- LICENSE
- MANIFEST.in
here you go :)
A few things to check
* I was not entirely sure which [BSD license](https://en.wikipedia.org/wiki/BSD_licenses) you preferred. I have gone for the newer 3-clause one.
* I have taken the year of the first commit for the [copyright notice year](http://www.copyrightlaws.com/international/copyright-notice-year/)
> add 3-clause BSD license

- aldjemy/orm.py
> Do not create a proxy model

- aldjemy/core.py
- aldjemy/orm.py
- aldjemy/table.py
- test_project/sample/tests.py
A PR to fix #63 as I promised.
> Allow custom metadata and schema

- .github/workflows/build.yml
We previously merged this in the WIP repo.
> Test with GitHub Actions

- .github/workflows/black.yml
- aldjemy/__init__.py
- aldjemy/apps.py
- aldjemy/core.py
- aldjemy/meta.py
- aldjemy/orm.py
- aldjemy/postgres.py
- aldjemy/sqlite.py
- aldjemy/table.py
- aldjemy/types.py
- aldjemy/wrapper.py
- setup.py
- test_project/manage.py
- test_project/sample/models.py
- test_project/sample/routers.py
- test_project/sample/tests.py
- test_project/sample/urls.py
- test_project/settings.py
- test_project/urls.py
- test_project_postgres/sample/apps.py
- test_project_postgres/sample/migrations/0001_initial.py
- test_project_postgres/sample/migrations/0002_auto_20170705_1331.py
- test_project_postgres/sample/tests.py
- test_project_postgres/test_project_postgres/settings.py
- test_project_postgres/test_project_postgres/urls.py
This was previously merged in the WIP repo
> Black formatting check

- aldjemy/wrapper.py
Rewrite nullop function as lambda
This was previously merged in the WIP repo
Authored by @Mogost originally
> Rewrite nullop function as lambda

- aldjemy/meta.py
- aldjemy/orm.py
- aldjemy/sqlite.py
- aldjemy/wrapper.py
Originally authored by @Mogost 
Wasn't merged yet in the WIP repo
> consistently use args/kwargs around project

- .github/workflows/black.yml
- .github/workflows/build.yml
Pull requests aren't currently running CI, which kinda defeats the purpose.
> Test pull requests

- aldjemy/postgres.py
- test_project_postgres/sample/tests.py
Rebased version of #93, so closes #93.
> Fix processing of Postgres ArrayField

- aldjemy/apps.py
- aldjemy/models.py
- aldjemy/orm.py
- aldjemy/table.py
- aldjemy/types.py
- aldjemy/wrapper.py
- test_project/sample/tests.py
since we will support only python>=3.6, django=>2.2; we don't need those anymore.
I will rebase it once #100 is merged.
That's all I could see. Please let me know if you see more changes like this
> Get rid of backward compatible code.

- test_project/frozen.txt
- test_project/sample/models.py
- tox.ini
Because now we run only on python3
> Remove six dependency

- .github/dependabot.yml
> Add dependabot integration

- .github/workflows/publish.yml
- README.rst
fixes #108 
- Not tested
- expect secret `PYPI_TOKEN`
> Automate publication of package to pypi

- .github/workflows/build.yml
Install things with a pattern I have used in another project.
> Clean up test matrix

- HISTORY.rst
- README.rst
- aldjemy/table.py
- pyproject.toml
- test_project/settings.py
> Delay reading settings

- pyproject.toml
This will make the readme show up as the long description for PyPI. When we do another release.
> Declare readme

- aldjemy/core.py
- test_project_postgres/sample/tests.py
SQLAlchemy is just re-using the DBApi2 connection created by django.
We assume the connection is clean and doesn't need to be rollback.
fixes #173
> Prevent transaction rollback on connection re-usage from SQLA.

- HISTORY.rst
changelog for next release 2.1.1
> prepare next release

- aldjemy/orm.py
We do want to have the FK constraints carried over the secondary table.
fixes #198
> Silence warning when mapping M2M fields

- aldjemy/orm.py
> Attempt at fixing the legacy mapper registration

- poetry.lock
- pyproject.toml
- test.sh
- tox.ini
> Switch to pytest

- .github/workflows/isort.yml
- aldjemy/__init__.py
- aldjemy/apps.py
- aldjemy/table.py
- poetry.lock
- pyproject.toml
- test_project/manage.py
- test_project/sample/models.py
- test_project/sample/tests.py
- test_project/settings.py
- test_project_postgres/sample/models.py
Make it compatible with black formatter
> Setup and configure isort

- aldjemy/orm.py
- test_project/sample/models.py
- test_project/sample/tests.py
- test_project_postgres/sample/tests.py
- tox.ini
> Solve Warning when m2m through model is provided by users

- .github/dependabot.yml
This will allow python 3.10 to be used on the CI
> Also upgrade our github actions

- poetry.lock
And attempt to fix the error between black and python-ast.
> Bump all dependencies at once

- .github/workflows/black.yml
- .github/workflows/build.yml
- .github/workflows/isort.yml
- .github/workflows/publish.yml
- HISTORY.rst
- pyproject.toml
- tox.ini
This is a breaking change, and will bump the major version. However, it's not a significant change, so we'll wait for something more substantive to need to change before we actually make the new release.
> Drop end of life Django and Python versions

- aldjemy/core.py
> Remove an outdated comment

- README.rst
- test_project/sample/models.py
Clean up the badges and remove a bit of uncovered code from Python 2 days.
> Easy coverage improvements

- aldjemy/core.py
- aldjemy/orm.py
- aldjemy/session.py
- aldjemy/table.py
- pyproject.toml
Drop some unneeded lines that I missed previously. Ignore some lines that aren't worth covering with automated tests because they're for optional compatibility testing. Enable branch coverage.
> Improve coverage configuration

- .github/workflows/build.yml
> Upgrade to artifact v4

- .github/workflows/build.yml
- HISTORY.rst
- pyproject.toml
- tox.ini
To avoid the desired backport from #327
> Re-add Django 4.1 compatibility
